Imports System.IO
Public Class frmSendBulkSms
    Dim sql As String
    Private Sub frmSendBulkSms_Load(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MyBase.Load
        sql = "select phone from " & GMod.ACC_HEAD & "  where len(phone)>=10"
        GMod.DataSetRet(sql, "phone")
        ComboBox1.DataSource = GMod.ds.Tables("phone")
        ComboBox1.DisplayMember = "phone"
    End Sub
    Dim sw As StreamWriter
    Dim sw1 As StreamWriter
    Private Sub Button1_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles Button1.Click
        Try

        
            'sw = File.CreateText("C:\SmsSendLogFile")

            ' sw1 = File.AppendText("C:\SmsFile")
            Dim msg As String
            Dim snd As New sendsms
            Dim i As Integer
            ' sw.WriteLine("Message Generated by the System")
            'For i = 0 To ComboBox1.Items.Count - 1
            'ComboBox1.SelectedIndex = i
            'sw1.WriteLine(TextBox1.Text & ":" & Now)
            For i = 0 To dgvoucher.Rows.Count
                msg = snd.send_sms(dgvoucher(0, i).Value.ToString, TextBox1.Text)
                'sw.WriteLine(msg & ":" & ComboBox1.Text)
            Next
            MsgBox("OK")
            ' sw.Close()
            'sw1.Close()
        Catch ex As Exception

        End Try
    End Sub
    Private Sub TextBox1_TextChanged(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles TextBox1.TextChanged
        Me.Text = "Charchter Count: " & TextBox1.Text.Length
        Wcont()
    End Sub
    Sub Wcont()
        Dim NoWocount() As String
        NoWocount = TextBox1.Text.Split(" ")
        Me.Text = Me.Text & " Word Count: " & NoWocount.Length
    End Sub
    Dim path As String
    Private Sub ComboBox1_SelectedIndexChanged(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles ComboBox1.SelectedIndexChanged

    End Sub

    Private Sub Button2_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles Button2.Click
        od.ShowDialog()
        path = od.FileName
    End Sub

    Private Sub btnShow_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnShow.Click
        Dim i As Integer
        Dim sql As String = ""
        Dim drv, crv As Double
        Try
            Dim MyConnection As System.Data.OleDb.OleDbConnection
            Dim DtSet As System.Data.DataSet
            Dim MyCommand As System.Data.OleDb.OleDbDataAdapter
            MyConnection = New System.Data.OleDb.OleDbConnection _
            ("provider=Microsoft.Jet.OLEDB.4.0;Data Source='" & path & "';Extended Properties=Excel 8.0;")
            MyCommand = New System.Data.OleDb.OleDbDataAdapter _
                ("select * from [mobile$]", MyConnection)
            MyCommand.TableMappings.Add("Table", "TestTable")
            DtSet = New System.Data.DataSet
            MyCommand.Fill(DtSet)
            dgvoucher.Rows.Add()
            dgvoucher(0, 0).Value = DtSet.Tables(0).Rows(0)(0).ToString.Trim
           


            For i = 0 To DtSet.Tables(0).Rows.Count
                'If DtSet.Tables(0).Rows(i)(0).ToString.Length > 0 Then
                dgvoucher.Rows.Add()
                dgvoucher(0, i).Value = DtSet.Tables(0).Rows(i)(0)
                'Else
                'Exit For
                ' End If
            Next
            'dgvoucher.DataSource = DtSet.Tables(0)
            MyConnection.Close()
        Catch ex As Exception
            MsgBox(ex.ToString)
        End Try
    End Sub
End Class